server:
  port: 9089

spring:
  datasource:
    url: jdbc:h2:./db/headHunter;AUTO_SERVER=true
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver

  mail:
    host: smtp.gmail.com
    username: nursultanzynwa@gmail.com
    password: rtbmgmtufihtxyua
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



  liquibase:
    change-log: classpath:/db/changelog/master.yaml
  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    root: info
  file:
    name: logs/spring.log