databaseChangeLog:
  - changeSet:
      id: insertDataAuthority
      author: Nursultan
      changes:
        - sql:
            comment: Insert data into authority
            sql: |
              insert into authorities (authority)
              values('FULL'), ('READ_ONLY');

  - changeSet:
      id: insertDataRoles
      author: admin
      changes:
        - sql:
            comment: Insert data into roles
            sql: |
              insert into roles(role, authority_id)
              values ('EMPLOYER', (select id from authorities where authority = 'FULL')),
                ('APPLICANT', (select id from authorities where authority = 'FULL'));
  - changeSet:
      id: insertDataUsers
      author: admin
      changes:
        - sql:
            sql: |
              insert into users(name, age, email, password, phoneNumber, avatar, accountType, enabled, role_id)
              VALUES
              ('John Doe', 30,'asdf@asdf.asdf', '$2a$12$gia1VaPRIlJ5rHQ6dI6ZkOUiFCDNRzWXqxybDny9j7LUveUfw3r2u', '1234567890', 'avatar.jpg',
              'EMPLOYER', TRUE, (select id from roles where role = 'EMPLOYER')),

              ('Jane Doe', 25, 'qwe@qwe.qwe', '$2a$12$R2WIT.PXQfBf.iHJCnl1RusjOWeIONtWXC5us4IDZB5o/SYLKpMqe', '0987654321', 'avatar.jpg',
              'APPLICANT', TRUE, (select id from roles where role = 'APPLICANT'));